Beer.create(name: 'Heineken', rating: 4)
Beer.create(name: 'Stella Artois', rating: 3)
Beer.create(name: 'Budweiser', rating: 2)
Beer.create(name: 'Bud Light', rating: 4)
Beer.create(name: 'Corona', rating: 4)
Beer.create(name: 'Goose Island IPA', rating: 5)
Beer.create(name: 'Duff', rating: 3)
Beer.create(name: 'Stone IPA', rating: 5)
Beer.create(name: 'Duvel Tripel Hop', rating: 4)
Beer.create(name: 'Brahma', rating: 1)
